### PR TITLE
Employ buffer-equal-constant-time

### PR DESCRIPTION
**Pull request by mbland**
This is just due diligence against potential timing attacks, per the [GitHub advice on securing webhooks](https://developer.github.com/webhooks/securing/) and [Coda Hale's "A Lesson in Timing Attacks"](http://codahale.com/a-lesson-in-timing-attacks/). Also note that [Node.js support for constant-time buffer comparisons in the standard crypto library](https://github.com/nodejs/node/issues/3043) may be forthcoming.

Also takes care of some latent lint errors, since I had screwed up the file spec in `gulpfule.js` the first time.

cc: @arowla @jeremiak @dhcole

### CODE REVIEW

**Comment by mbland** [comment]
Just a little ping... Hoping to get this and 18F/pages-server#4 and 18F/pages-server#5 in and deployed in the next couple days.

**Comment by mbland** [comment]
Ping... If no one can get to this today or tomorrow, I may go ahead and merge it, but I'll be happy to wait a while if anyone can pledge bandwidth within that time frame.

**Comment by dhcole** [comment]
:+1: looks good to me.

**Comment by mbland** [comment]
Thanks, @dhcole!

**Pull request merged**
